# site info
site_name: '@dphans'
site_description: 'A Material Design theme for MkDocs'
site_author: '@dphans'
site_url: 'https://dphans.github.io/'
copyright: 'Copyright &copy; 2019 @dphans'

# source docs
repo_name: 'dphans/dphans.github.io'
repo_url: 'https://github.com/dphans/dphans.github.io'

# pages
nav:
  - Home: index.md
  - Profile: profile.md
  - Policies:
      - 'Pocket Cantonese': 'policies/pocket_cantonese.md'
      - 'Pocket Cantonese (Tiếng Việt)': 'policies/pocket_cantonese_vi.md'
  - 2015:
      - 'Implementing TURN server on CentOS': '2015/webrtc_custom_stun_turn.md'

# theme
theme:
  name: 'material'
  palette:
    primary: 'orange'
    accent: 'orange'
  font:
    text: 'Google Vietnamese'
    code: 'IBM Plex Mono'
  logo:
    icon: 'devices'

# contact info
extra:
  social:
    - type: 'github'
      link: 'https://github.com/dphans/'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/in/dphans/'

# code highlight
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true

# plugins
plugins:
  - search
  - minify:
      minify_html: true

# customize sources
extra_css:
  - 'assets/styles/fonts.css'
